DELIMITER $$
CREATE TRIGGER table_insert
BEFORE INSERT ON room
FOR EACH ROW
BEGIN
  INSERT INTO roomseq VALUES (NULL);
  SET NEW.roomid = CONCAT('R', LPAD(LAST_INSERT_ID(), 3, '0'));
END$$
DELIMITER ;